#!/usr/bin/env perl

use warnings;
use strict;
use autodie qw(:all);

my $version = shift or die "no version";

`git rm gumbo-*.tar.gz`;
`git submodule foreach git checkout v$version`;
`git commit -m "update gumbo source" gumbo-src`;
`rm -fr gumbo-src/gumbo-*.tar.gz`;
`cd gumbo-src; ./autogen.sh && ./configure && make dist`;
`cp -a gumbo-src/gumbo-*.tar.gz .`;
`git add gumbo-*.tar.gz`;
`cat MANIFEST | perl -ne 'm{^gumbo-.*\.tar\.gz\$} || print' > MANIFEST`;
`./Build manifest`;
`git add MANIFEST`;
`git commit -m "update gumbo tarball" gumbo-* MANIFEST`;
